# Generated by Django 4.0.4 on 2022-05-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 19, 21, 29, 57, 688056)),
        ),
    ]
