# Generated by Django 4.0.4 on 2022-05-19 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_m_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 19, 21, 30, 43, 441345)),
        ),
    ]
