# Generated by Django 4.0.4 on 2022-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_no', models.IntegerField(default=0)),
                ('u_id', models.CharField(max_length=20)),
                ('b_title', models.CharField(max_length=200)),
                ('b_content', models.CharField(max_length=3000)),
                ('b_date', models.DateField(auto_now=True)),
                ('b_group', models.IntegerField(default=0)),
                ('b_step', models.IntegerField(default=0)),
                ('b_indent', models.IntegerField(default=0)),
                ('b_hit', models.IntegerField(default=0)),
                ('b_img', models.CharField(max_length=200)),
            ],
        ),
    ]
